name: Continuous Deployment
on:
  repository_dispatch:
    types:
      - new-release
jobs:
  build:
    name: Homebrew
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Download Archive
        run: wget https://github.com/fraserdarwent/dl/releases/download/${{ github.event.client_payload.version }}/dl-${{ github.event.client_payload.version }}-darwin-amd64.zip
      - name: Update Formula
        run: |
          URL=dl-${{ github.event.client_payload.version }}-darwin-amd64.zip       
          SHA=$( shasum -a 256 dl-${{ github.event.client_payload.version }}-darwin-amd64.zip )          
          VERSION=${{ github.event.client_payload.version }}
          sed -i "s/\${SHA}/${SHA}/g" Formula/dl.rb
          sed -i "s/\${URL}/${URL}/g" Formula/dl.rb
          sed -i "s/\${VERSION}/${VERSION}/g" Formula/dl.rb
          cat Formula/dl.rb
      - name: Test Formula
        run:  |
          brew audit --strict --new-formula --online Formula/dl.rb
