name: Continuous Deployment
on:
  repository_dispatch:
    types:
      - new-release
jobs:
  build:
    name: Homebrew
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Export Version
        id: version
        run: echo '::set-output name=tag::0.0.6'
      - name: Download Archive
        run: wget https://github.com/fraserdarwent/dl/releases/download/${{ steps.version.outputs.tag }}/dl-${{ steps.version.outputs.tag }}-darwin-amd64.zip
      - name: Update Formula
        run: |
          URL=https://github.com/fraserdarwent/dl/releases/download/${{ steps.version.outputs.tag }}/dl-${{ steps.version.outputs.tag }}-darwin-amd64.zip
          SHA=$( shasum -a 256 dl-${{ steps.version.outputs.tag }}-darwin-amd64.zip )          
          VERSION=${{ steps.version.outputs.tag }}
          sed -i.original "s|\${SHA}|${SHA}|g" Formula/dl.rb
          sed -i.original "s|\${URL}|${URL}|g" Formula/dl.rb
          sed -i.original "s|\${VERSION}|${VERSION}|g" Formula/dl.rb
          cat Formula/dl.rb
