name: Continuous Deployment
# on:
#   repository_dispatch:
#     types:
#       - new-release
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    name: Homebrew
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Export Version
        id: version
        run: echo '::set-output name=tag::0.0.6'
      - name: Download Archive
        run: wget https://github.com/fraserdarwent/dl/releases/download/${{ steps.version.outputs.tag }}/dl-${{ steps.version.outputs.tag }}-darwin-amd64.zip
      - name: Update Formula
        run: |
          export URL=https://github.com/fraserdarwent/dl/releases/download/${{ steps.version.outputs.tag }}/dl-${{ steps.version.outputs.tag }}-darwin-amd64.zip
          export SHA=$(shasum -a 256 dl-${{ steps.version.outputs.tag }}-darwin-amd64.zip | awk '{print $1}')          
          export VERSION=${{ steps.version.outputs.tag }}
          envsubst < template.rb > Formula/dl.rb
          cat Formula/dl.rb
      - name: Update state files
        uses: EndBug/add-and-commit@v5
        with:      
          author_name: GitHub Action
          author_email: action@github.com
          message: Update Formula
          add: Formula/dl.rb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
